### PR TITLE
Wallet route

### PR DESCRIPTION
**Pull request by wildmolasses**
deployed multisig wallets can be linked to via ogg.scopelift.co/wallet/[address]

### CODE REVIEW

**Review by apbendi — CHANGES_REQUESTED** [review]
Looks and works great! Two minor requests:

1. When on a wallet detail page, can we add a "Back" or "Home" link to return to the main page?
2. Right now, if you put in an invalid address, the codebase throws. We should fail more gracefully if possible, and show a "Multisig contract not found at this address" message on the page.

One other note: mind rebasing this to `master` now that the other PR is merged to resolve the conflicts? Thanks!

**Comment by wildmolasses** [comment]
> 1. When on a wallet detail page, can we add a "Back" or "Home" link to return to the main page?

currently this is done with the "Switch" button

Screen Shot 2021-07-15 at 10 08 26 PM

I think a UI improvement could be great here, but do you mind if we punt to future UI-focused PR?

> 2\. Right now, if you put in an invalid address, the codebase throws. We should fail more gracefully if possible, and show a "Multisig contract not found at this address" message on the page.

Makes sense! Great point! Change coming up.

**Comment by wildmolasses** [comment]
current status:

Screen Shot 2021-07-15 at 10 40 13 PM

@apbendi , is there any way to tell whether the address they've selected is in fact a multisig contract instance? 2 ideas that come to mind are:
- use https://docs.ethers.io/v5/single-page/#/v5/api/providers/provider/-%23-Provider-getCode
- try to use contract getter e.g. `owners` and if there is no result then throw

**Comment by apbendi** [comment]
@wildmolasses I think the `getCode` route is probably the safest, as it ensure the UI is seeing *exactly* the contract it is developed to interact with. Given the sensitivity of a multisig this is probably the way we should go, unless there is an implementation issue.

**Review by apbendi — APPROVED** [review]

**Pull request merged**
